### ISSUE TITLE
metadata.json missing from release

### ISSUE THREAD

**Issue by nud** [willsoto/ng-chartist#104]
Hi

While using ng-xi18n on an Angular2 project that uses ng-chartist, I get the following error:

```Error: Unexpected value 'ChartistModule in <snap>/node_modules/ng-chartist/dist/chartist.component.d.ts...```

Using regular builds through webpack works fine though, so it's just the ng-xi18n command that fails. Presumably other ng command-line tools might exhibit the same problems.

According to https://github.com/angular/angular/issues/13240 the reason would be that metadata.json is missing from the release.

**Comment by warmans** [comment]
This module does not work with angular-cli aot builds due to a similar error:

```
ERROR in Unexpected value 'ChartistModule in .../node_modules/ng-chartist/dist/chartist.component.d.ts' imported by the module 'AppModule in .../src/app/app.module.ts'. Please add a @NgModule annotation.
```

I think it just needs the module annotations in the code. Maybe you can do the same thing with a metadata file but the standard way would be an annotation as far as I know.
