### ISSUE TITLE
usage of ng-chartist

### ISSUE THREAD

**Issue by shreenil** [willsoto/ng-chartist#106]
i have installed all the dependencies of ng-chartist in angular-cli.
also imported it in the app.module file. But my problem is i cant find the usage with ng2 in chartist documentation. How to use it in html as well as ts file?

**Comment by willsoto** [comment]
I have examples in the [README](https://github.com/willsoto/ng-chartist#then-use-it-in-your-app-like-so). Let me know if these aren't sufficient.
