### ISSUE TITLE
outdated chartist dependency

### ISSUE THREAD

**Issue by yohny** [willsoto/ng-chartist#1217]
This library has a peer dependency on chartist `^0.11.4`, but that's very old, the current released version is `1.1.2` (at the time of writing this)

**Comment by willsoto** [comment]
FWIW, I wouldn't call it "very old" - it was only released a couple of weeks ago and contains a bunch of breaking changes. 

You are welcome to submit a PR with all the necessary changes (you can see some of the errors on #1218) otherwise I will tackle this within the next few days.
