### ISSUE TITLE
How to add click event to a BarChartist ?

### ISSUE THREAD

**Issue by govireliefapps** [willsoto/ng-chartist#123]
Hi there,
I am trying to add events on my Bar Chartist in a Ionic app: when I click on a bar, I would like to get information (value and label of the bar) and do stuff with this information. I think that an event is the best way to do so.
I looked into the [chartist.js documentation](http://gionkunz.github.io/chartist-js/api-documentation.html), but I can't find anything else that the "draw" event which is not usefull in my situation...
Is it possible to define a click event on a specific bar of the chart ?
Sorry for my little knowledge of JS and AngularJS :/

**My .html file:**
`<x-chartist [type]=type [data]=data [options]=options [events]=events></x-chartist>`

**My .ts file:**
```
this.type = "Bar";
this.data = {
//I define labels and series arrays before
      labels: labels,
      series: [series]
    };
this.options = {
//Options about displaying
    };
this.events = {
// ??
      }
    };

```

**Comment by willsoto** [comment]
I think it makes more sense to raise this issue with the main project: https://github.com/gionkunz/chartist-js
