### ISSUE TITLE
Angular 15 ng-chartist is not working

### ISSUE THREAD

**Issue by Urvishdudhagara** [willsoto/ng-chartist#1324]
>> chart type is not working on Angular 15 version

![Screenshot from 2022-12-13 13-52-15](https://user-images.githubusercontent.com/109670606/207263503-d669f889-37c9-4515-8c02-ac0995358826.png)

**Comment by hakimio** [comment]
This is not related to Angular 15. `ng-chartist` usage changed in the latest version: https://github.com/willsoto/ng-chartist#usage
