### ISSUE TITLE
'ɵɵComponentDeclaration' error on angular 14

### ISSUE THREAD

**Issue by Ali-Azizi** [willsoto/ng-chartist#1335]
Hello there,

I'm trying to use your package on angular 14 but I face with below error:

`
Error: node_modules/ng-chartist/lib/chartist.component.d.ts:69:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

69     static ɵcmp: i0.ɵɵComponentDeclaration<ChartistComponent, "x-chartist", never, { "configuration": "configuration"; "events": "events"; }, { "initialized": "initialized"; }, never, never, false, never>;
`

I think so this error is related to angular version.
Thanks,

**Comment by willsoto** [comment]
Please provide a minimal reproduction. 

Also, if you are stuck on Angular 14 please use the last version prior to the v15 upgrade. The package does the same thing, it's just about Angular version.

**Comment by Ali-Azizi** [comment]
Great, thanks for your response.
I have same problems with other packages after updating to angular v15, so I've downgraded to v14 again.

Anyway thanks for your help.
