### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by brunolsantos** [willsoto/ng-chartist#140]
I'm trying to use a tooltip plugin but this error keeps appearing
[This](http://imgur.com/a/Glh55) image shows where i added the plugin, i followed every step that you have on your demo folder, but couldn't load plugin.

**Comment by brunolsantos** [comment]
Just found a similar issue:
https://github.com/willsoto/ng-chartist/issues/105

**Comment by brunolsantos** [comment]
Tried to do the same as the above issue but the problem continues. I manage to use an older plugin download, instead of `npm install chartist-plugin-tooltip**s**`  i used `npm install chartist-plugin-tooltip` but it came without css.

Do you have any idea how i can fix it?

**Comment by willsoto** [comment]
Seems like an issue with the plugin? I would file an issue there if you haven't already.
