### ISSUE TITLE
Cannot find type definition file for 'chartist'.

### ISSUE THREAD

**Issue by ikismail** [willsoto/ng-chartist#184]
Hello, I'm getting this issue while serving my application can anyone figure this out?

**Version**:  "ng-chartist": "^1.1.1",

`ERROR in node_modules/ng-chartist/dist/chartist.component.d.ts(1,23): error TS2688: Cannot find type definition file for 'chartist'.`

**Comment by willsoto** [comment]
Did you install the typings for Chartist?
https://github.com/willsoto/ng-chartist/blob/master/README.md#additionally-typings-for-the-chartist-library-need-to-be-installed

**Comment by ikismail** [comment]
@willsoto  yes I did still got the same 🤷

**Comment by willsoto** [comment]
Without more information, it's hard to debug. What does your tsconfig look like? Do you have other types you are importing?
