### ISSUE TITLE
 Accessing Chart Object and Using APIs inside angular component while using <x-chartist><x-chartist /> 

### ISSUE THREAD

**Issue by 305425** [willsoto/ng-chartist#199]
I am trying to access the Chart object in side my angular component. And also trying to access
Chartist API like querySelector() .

Please let me know is there any way to do it while using ng-chartist , if not can we open an issue to add this feature.

Thanks in advance

**Comment by willsoto** [comment]
The `chart` instance lives on the component ([here](https://github.com/willsoto/ng-chartist/blob/master/src/chartist.component.ts#L112)). But I am not familiar enough with Angular on how you might access it.

> And also trying to access Chartist API like querySelector() .

Couldn't you just import Chartist?

**Comment by 305425** [comment]
Thanks for immediate reply.

Regarding chart instance , yes chart property is exposed as a public member but  struggling to access it in side my component.Could u please give some example how we can access the instance.

And yes I am able to import Chartist . But not able to figure out how to call this api. Also tried to search in different forum , not able to get any help.
An example would be highly appreciated corresponding to this scenario.
Thanks

**Comment by willsoto** [comment]
I don't use Angular at all, so unfortunately I can't really help you out there. As far as that Chartist API goes, it seems straightforward: https://gionkunz.github.io/chartist-js/api-documentation.html#chartistsvg-function-queryselector
