### ISSUE TITLE
LabelInterpolationFnc value is null when I set x and y values

### ISSUE THREAD

**Issue by thiwanka-g** [willsoto/ng-chartist#206]
Hi,
I'm trying to get a timeseries chart working like the example : [https://gionkunz.github.io/chartist-js/examples.html#example-timeseries-moment](url)

But the value passed into the LabelInterpolationFnc is null.

`    var dataset=[
      {
        "name":"Active power ad",
        "data":[
          {"x":"2018-06-27 00:00:58","y":31.550001144409},
          {"x":"2018-06-27 00:01:58","y":30},
          {"x":"2018-06-27 00:02:59","y":29.789999961853},
          {"x":"2018-06-27 00:04:00","y":15.530000209808},
          {"x":"2018-06-27 00:05:00","y":23.219999313354},
          {"x":"2018-06-27 00:06:01","y":23.549999713898},
          {"x":"2018-06-27 00:07:01","y":25.909999847412},
          {"x":"2018-06-27 00:08:02","y":20.280000209808},
          {"x":"2018-06-27 00:09:03","y":23.789999961853},
          {"x":"2018-06-27 00:10:03","y":21.280000209808},
          {"x":"2018-06-27 00:11:04","y":21.839999675751},
          {"x":"2018-06-27 00:12:05","y":21.699999809265}
        ]
      },
      {
        "name":"Active power ad",
        "data":[
          {"x":"2018-06-27 00:00:59","y":14.400000095367},
          {"x":"2018-06-27 00:02:00","y":14.439999818802},
          {"x":"2018-06-27 00:03:00","y":14.340000152588},
          {"x":"2018-06-27 00:04:01","y":14.410000324249},
          {"x":"2018-06-27 00:05:02","y":14.370000123978},
          {"x":"2018-06-27 00:06:02","y":14.400000095367},
          {"x":"2018-06-27 00:07:03","y":14.389999866486},
          {"x":"2018-06-27 00:08:04","y":14.420000314713},
          {"x":"2018-06-27 00:09:04","y":14.389999866486},
          {"x":"2018-06-27 00:10:05","y":14.44000005722},
          {"x":"2018-06-27 00:11:06","y":14.410000085831},
          {"x":"2018-06-27 00:12:06","y":14.460000038147}
        ]
      }
    ];

    this.type="Line";
    this.data = {
      series:dataset     
    };
    this.options = {
      axisX: {
        labelInterpolationFnc: function(value, index, labels) {
          console.log(value);
          return moment(value).format('MMM D');
        }
      },
    };`

Any help will be greatly appreciated :nerd_face:

**Comment by willsoto** [comment]
Glad you figured it out!
