### ISSUE TITLE
Angular 7 production build issue

### ISSUE THREAD

**Issue by nitinht1988** [willsoto/ng-chartist#214]
Hello there,

After upgrading my project to Angular 7 i am getting below error while running `ng build --prod` command. `ng serve` is working fine.

> ERROR in : Unexpected value 'ChartistModule in E://node_modules/ng-chartist/bundles/ng-chartist.umd.js' imported by the module 'ChartsNg2Module in E://src/app/charts/charts.module.ts'. Please add a @NgModule annotation.

When i hover over the import statement in the module file it says:

> Could not find a declaration file for module 'ng-chartist'. 'e:/node_modules/ng-chartist/bundles/ng-chartist.umd.js' implicitly has an 'any' type.
>   Try `npm install @types/ng-chartist` if it exists or add a new declaration (.d.ts) file containing `declare module 'ng-chartist';`
> [ts]
> Could not find a declaration file for module 'ng-chartist'. 'e:/node_modules/ng-chartist/bundles/ng-chartist.umd.js' implicitly has an 'any' type.
>   Try `npm install @types/ng-chartist` if it exists or add a new declaration (.d.ts) file containing `declare module 'ng-chartist';`

"@angular/core": "7.0.0",
 "ng-chartist": "^2.0.0-beta.1",
    "@types/chartist": "0.9.43",
    "chartist": "0.11.0",

Thank you.

**Comment by willsoto** [comment]
This has been an on-going issue - See #198 #150. I don't use Angular on a regular basis and so I really don't know how to fix this. I am open to PRs.

**Comment by hakimio** [comment]
@willsoto 
You have to properly generate your library using angular cli like explained in the following guide:
https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5

Otherwise Angular 6 and 7 aot builds will fail (which is rather important).
If you are not planning to update this library, you should state in the Readme that the library is only compatible with Angular 4 and 5.

**Comment by willsoto** [comment]
I'll see if I can find some time next weekend. 

As I said before, I am more than willing to review a PR if someone opens one and the issue would probably get resolved faster if someone does go that route.

**Comment by willsoto** [comment]
Closed via #216
