### ISSUE TITLE
Unable to visit ng-chartist github pages

### ISSUE THREAD

**Issue by pnutdev** [willsoto/ng-chartist#251]
Documentation and demo links  are not available. Look like something messed up with github pages of this repository!

https://willsoto.github.io/ng-chartist/ is not available!

**Comment by bargross** [comment]
Same here, not able to view anything

**Comment by willsoto** [comment]
@hakimio anything you need from here?

**Comment by willsoto** [comment]
Fixed. Sorry about that.
