### ISSUE TITLE
Update Diagram

### ISSUE THREAD

**Issue by johoehn** [willsoto/ng-chartist#253]
Is it possible to update/redraw diagram, when labels are changed dynamically?

**Comment by hakimio** [comment]
Yes, you can do that. Check out the live chart updating example to see how it can be done: https://github.com/willsoto/ng-chartist/blob/master/projects/ng-chartist-demo/src/app/components/live-chart.component.ts#L53

Basically after updating the labels you just have to make a shallow copy of the "data" object.
