### ISSUE TITLE
Installation instructions don't work on Angular 7

### ISSUE THREAD

**Issue by hanneshauer** [willsoto/ng-chartist#255]
When following the installation instructions, section 'Add Chartist CSS styles to your application', on Angular 7.0.3 the application compiles successfully but throws the following error upon opening the site in the browser:

> Expected 'styles' to be an array of strings.

Using the .scss instead of the .css file works:
```
"styles": [
  "node_modules/chartist/dist/scss/chartist.scss",
  "src/style.scss"
],
```

**Comment by hakimio** [comment]
The demos in this project use Angular 7. The issue might be that you copied the code wrong.
