### ISSUE TITLE
How to add point-label on mouseover event in line charts?

### ISSUE THREAD

**Issue by momame** [willsoto/ng-chartist#286]
I want to the user to be able to check each point's values upon hovering mouse. How can I achieve it? 
I already reach to this point i.e. I can get each pint value upon hovering:

if (data.type === 'point') {
               $(data.element._node).on('mouseover', function () {
         
          console.log(data.value.y);
        });

**Comment by hakimio** [comment]
Have you seen [Tooltip plugin for Chartist.js (Updated)](https://github.com/LukBukkit/chartist-plugin-tooltip) ([npm](https://www.npmjs.com/package/chartist-plugin-tooltips-updated))?

**Comment by hakimio** [comment]
@momame did you manage to get the chart tooltips working?

**Comment by jesteban19** [comment]
> Have you seen [Tooltip plugin for Chartist.js (Updated)](https://github.com/LukBukkit/chartist-plugin-tooltip) ([npm](https://www.npmjs.com/package/chartist-plugin-tooltips-updated))?

I installed plugin but not working.

`import ChartistTooltip  from 'chartist-plugin-tooltips-updated';`

```js
ChartistTooltip({
                currency: '$',
                pointClass:'my-cool-point',
                appendToBody: true,
            })
```

**Comment by hakimio** [comment]
Did you include it in your chart's "plugins" config?
```js
{
  plugins: [
    ChartistTooltip()
  ]
}
```

**Comment by hakimio** [comment]
In case someone still needs help getting the plugin to work, here is an example usage:

**tooltip-chart.component.ts**:
```ts
import ChartistTooltip from 'chartist-plugin-tooltips-updated';

@Component({
  selector: 'tooltip-chart',
  template: `
    <x-chartist [data]="data" [type]="type" [options]="options"></x-chartist>
  `
})
export class TooltipChartComponent {
  type: ChartType = 'Line';
  data: IChartistData = {
    labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    series: [[12, 9, 7, 8, 5], [2, 1, 3.5, 7, 3], [1, 3, 4, 5, 6]]
  };
  options: ILineChartOptions = {
    plugins: [
      ChartistTooltip()
    ]
  };
}

```
**CSS styles** added to `angular.json`:
```
"styles": [
  "node_modules/chartist/dist/chartist.css",
  "node_modules/chartist-plugin-tooltips-updated/dist/chartist-plugin-tooltip.css",
  "projects/ng-chartist-demo/src/styles.css"
]
```

Also, in case you have to fix tooltip offset:
```css
:host::ng-deep .chartist-tooltip {
  margin-left: 15px;
  margin-top: 35px;
}
```

**Comment by hakimio** [comment]
[Tooltip example](https://github.com/willsoto/ng-chartist/blob/master/projects/ng-chartist-demo/src/app/components/tooltip-chart.component.ts) is now part of the demo project.
