### ISSUE TITLE
ChartistModule is empty

### ISSUE THREAD

**Issue by netronicus** [willsoto/ng-chartist#537]
i'm trying to install the package with npm i ng-chartist, the installed version is 4.1.0, I'm trying to use it but it says that the x-chartis is not a known component and checking the module structure I detected that ChartistModule is almost empty, just this:

export declare class ChartistModule {
}

**Comment by willsoto** [comment]
Not sure what the issue would be. The component is listed right here: https://github.com/willsoto/ng-chartist/blob/50a97574da5b48d75f44cb5b136ee7427c86d593/projects/ng-chartist/src/lib/chartist.module.ts#L4-L9

Are you looking at the **types** and not the source code?

**Comment by netronicus** [comment]
I'm looking at ng-chartist inside node_modules, I can't figure it out why is it missing, trying to install version 3.1.0 and the same has occurred

**Comment by willsoto** [comment]
Seems like it might be an issue specific to you. This module is still pretty widely used and I haven't seen any other issues regarding this. I'll keep this issue open in case others _are_ just now having this issue.

**Comment by willsoto** [comment]
It seems like you are looking at the typings and not the actual source code:

```ts
export declare class ChartistModule {
// --------^ this is what indicates to me it is the typings
}
```

If you wish to share some code I can try and help. I am closing this issue since there is nothing actionable here.

**Comment by hakimio** [comment]
Just for future reference: Angular throws "x-chartist is not a known component" error when you forget to [import ChartistModule](https://github.com/willsoto/ng-chartist#usage).
