### ISSUE TITLE
Update @types/chartist dependency

### ISSUE THREAD

**Issue by FranciscoKnebel** [willsoto/ng-chartist#554]
Last update to [this dependency](https://www.npmjs.com/package/@types/chartist) was in Aug 2020, to 0.11.0
From what I understood, @types/chartist 0.11.0 supports Typescript 3 and 4, and 0.9.* is Typescript 2.

Is there any other particular reason why ng-chartist doesn't support it?

**Comment by hakimio** [comment]
@willsoto can you update all dependencies and publish new package?

**Comment by willsoto** [comment]
Sure

**Comment by willsoto** [comment]
Published under [v5.0.0](https://github.com/willsoto/ng-chartist/blob/main/CHANGELOG.md#500-2021-05-27). Please re-open if you have any issues with this release.
