### ISSUE TITLE
Does Not Work with Angular 11

### ISSUE THREAD

**Issue by Crypt0Graphic** [willsoto/ng-chartist#603]
I use Angular 11 in Local Project, 12 in Global. Can't install:

![Screen Shot 2021-06-21 at 02 32 02](https://user-images.githubusercontent.com/9743846/122691536-f841de80-d238-11eb-8195-7dab688f88bf.png)

Then i used --force option and imported it. It can't build:

```
Error: ./node_modules/ng-chartist/fesm2015/ng-chartist.js 186:10-28
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

Error: ./node_modules/ng-chartist/fesm2015/ng-chartist.js 132:0-27
"export 'ɵɵngDeclareClassMetadata' (imported as 'i0') was not found in '@angular/core'
```

**Comment by hakimio** [comment]
v5 requires Angular 12 like peer dependency error indicates.
You can use v4.1 with Angular 11.
