### ISSUE TITLE
Tooltip Problem

### ISSUE THREAD

**Issue by Crypt0Graphic** [willsoto/ng-chartist#650]
I installed chartist-plugin-tooltips-updated like in your tooltip demo.

But i get error like:

`Could not find a declaration file for module 'chartist-plugin-tooltips-updated'. '`

So can not use ChartistTooltip option. Any advice?

**Comment by willsoto** [comment]
That seems like an issue with that library and its typings. It's not related to this library. If you believe it is, feel free to reopen with a minimal reproduction showing that the problem is with this library.

**Comment by hakimio** [comment]
@Crypt0Graphic can you create reproduction project?

**Comment by Crypt0Graphic** [comment]
No d.ts file in chartist-plugin-tooltips-updated. I opened issue under that library ok.

**Comment by hakimio** [comment]
@Crypt0Graphic it doesn't have to have `*.d.ts` file for it to compile.

**Comment by willsoto** [comment]
I don't think that package has any typings: https://www.typescriptlang.org/dt/search?search=chartist-plugin

You will need to stub them out like:

```ts
declare module 'chartist-plugin-tooltips-updated';
```

**Comment by hakimio** [comment]
@Crypt0Graphic did you install the right package? `chartist-plugin-tooltips-updated` not `chartist-plugin-tooltips`.
https://github.com/LukBukkit/chartist-plugin-tooltip

**Comment by Crypt0Graphic** [comment]
Yes. I installed chartist-plugin-tooltips-updated a couple times. Then i tried old one also. All generates error because no typings.

**Comment by hakimio** [comment]
@willsoto it's not a typings issue.

**Comment by Crypt0Graphic** [comment]
Already i used code in your demos.

**Comment by hakimio** [comment]
If it works in the demo project, it should work in your project. Provide reproduction demo, so I could take a look.

**Comment by Crypt0Graphic** [comment]
Your code is here that i tried:

https://github.com/willsoto/ng-chartist/blob/main/projects/ng-chartist-demo/src/app/components/tooltip-chart.component.ts

Maybe you added typings manually to the node_modules. I can't see that. But package does not work i am sure.

**Comment by willsoto** [comment]
@hakimio I believe it is a typings issue given the error. TypeScript _will refuse to compile modules it doesn't have declarations for._ There may be ways to disable that but, by default, TypeScript will raise an error when a module has no typings. 

If you'd like to understand why it is raising an issue in his case and not in our demo then go for it, but I maintain this isn't an issue with this library.

**Comment by Crypt0Graphic** [comment]
By the way. My Global Angular is 12+. Local is 11. Your demo probably use an older version.

**Comment by hakimio** [comment]
@willsoto I agree, it's not an issue with this library. No worries.

@Crypt0Graphic Global cli version doesn't matter. If you want me to help, provide reproduction. Until then I'll have to assume it's an issue on your end.
