### ISSUE TITLE
Add access to chartist API or underlying object

### ISSUE THREAD

**Issue by yohny** [willsoto/ng-chartist#803]
Currently its not possible to access underlying chatrist object and API (https://gionkunz.github.io/chartist-js/api-documentation.html) when using this library, which is quite limiting. For example it would be handy to be able co call chartist's `update()` method (https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update) to solve issues with revealing hidden element containing chartist. (https://github.com/gionkunz/chartist-js/issues/119).
Probably the simplest solution would be to expose underlying chartist object, so whatever API changes are made in chartist itself they will be available in this library without need to duplicate them.

**Comment by hakimio** [comment]
You can use [initialized event](https://github.com/willsoto/ng-chartist/blob/main/projects/ng-chartist/src/lib/chartist.component.ts#L106) to get Chartist instance.

**Comment by yohny** [comment]
didn't know about that one, thanks :+1: 
anyway the `update()` method has all parameters optional according to linked docs, but in your type definition at least `data` param is required
