### ISSUE TITLE
Improve error message on incorrect chart type

### ISSUE THREAD

**Issue by Aides359** [willsoto/ng-chartist#97]
Using a incorrect chart type value throws a generic
```Unhandled Promise rejection: Cannot read property 'apply' of undefined ; Zone: angular ; Task: Promise.then ;```
with no reference to angular2-chartist source code in the stack trace.

While this should be handled by the type check on `ChartType`, there might still be situations where an incorrect chart type might slip through.

A better error message describing the error would be really helpful then.

**Comment by AmitMY** [comment]
I had the same error, took me a while to figure it out

**Comment by willsoto** [comment]
This seems reasonable. I'll take a look.

**Comment by Aides359** [comment]
The check should be done right before https://github.com/willsoto/angular2-chartist/blob/master/src/chartist.component.ts#L88.

Would you rather prefer something along the lines of
```if(type !== 'Bar' && line !== 'Line' && ...) | if(!type.match(/^(Bar|Line|...)$/))
    throw new Error(`${type} is not a valid chart type`);```

or rather
```let chartClass = (<any>Chartist)[type];
if(!chartClass)
    throw new Error(`${type} is not a valid chart type`);

this.chart = chartClass(...args);```

The latter is more flexible and requires less redundancy (if you ever support more chart types you'd have to remember to update the first solution), however it would not properly throw if any property name of Chartist was passed (although this would probably be an edge case).

The best solution would be to check on the valid values of the `ChartType` type but AFAIK this is not possible (maybe it is with some decorator magic or by reworking the type to be created from a string[], but I don't think that's possible).

**Comment by willsoto** [comment]
Yup, the latter for sure. Something like:

```
const chart = (<any>Chartist)[type];

if (!chart) {
  Promise.reject(new Error(`${type} is not a valid chart type`)); // very import we reject the promise
}

// continue
```

If you plan on making a PR. A test for this should be pretty straightforward.

**Comment by Aides359** [comment]
Actually AFAIK a throw inside a promise automatically rejects the promise but yes, I also prefer the explicit reject.

I'll see what I can do.

**Comment by Aides359** [comment]
Sorry, was quity busy.
Thanks 👍
